version: '3.9'
services:
  webapp:
    image: dimmaryanto93/nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: mainline
    environment:
      - NGINX_PORT=80
      - NGINX_DOMAIN_NAME=dev01.dimas-maryanto.com
      - NGINX_ROOT_DOCUMENT=/var/www/html
