version: '3.9'
services:
  backend:
    image: php:8.0-apache
    ports:
      - 8080:80
    depends_on:
      - db
      - migrate-tools
    profiles: [ "prod" ]
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    profiles: [ "debug" ]
    ports:
      - 33306:80
    environment:
      - MYSQL_ROOT_PASSWORD
      - PMA_HOST=db
    depends_on:
      - db
  migrate-tools:
    image: flyway/flyway:latest-alpine
    profiles: [ "dev" ]
    environment:
      - FLYWAY_EDITION
    command: [ "-user=${MYSQL_USER}", "-password=${MYSQL_PASSWORD}", "-url=jdbc:mysql://db:3306/${MYSQL_DATABASE}", "info" ]
    depends_on:
      - db
volumes:
  mysql_data:
