version: '3.9'
services:
  webapp:
    build:
      dockerfile: Dockerfile-nginx
      context: .
      args:
        NGINX_VERSION: mainline
    ports:
      - "80:80"
  backend:
    build:
      dockerfile: Dockerfile-php
      context: .
      args:
        PHP_VERSION: 8.0-apache
  db:
    environment:
      - POSTGRES_PASSWORD=secretPassword
      - POSTGRES_USER=user_prod
      - POSTGRES_DB=prod_db
