version: '3.9'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    networks:
      - backend
      - frontend
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
  proxy:
    image: nginx:mainline
    ports:
      - "80:80"
    environment:
      - WORDPRESS_HOST=wordpress
      - WORDPRESS_PORT=80
      - WORDPRESS_CONTEXT_PATH=/
    networks:
      - frontend
    volumes:
      - type: bind
        source: ./nginx/wordpress-proxy.nginx.template.conf
        target: /etc/nginx/templates/default.conf.template
volumes:
  mysql_data:
networks:
  frontend:
  backend:
