version: '3.8'
services:
  proxy:
    image: nginx:alpine
    ports:
      - 80:80
    environment:
      - APPLICATION_PORT=80
      - NGINX_ROOT_DOCUMENT=/usr/share/nginx/html
      - BACKEND_HOST=backend
      - BACKEND_PORT=80
      - BACKEND_CONTEXT_PATH=/
    volumes:
      - ./default.template.conf:/etc/nginx/templates/default.conf.template
  backend:
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html
    expose:
      - 80
