version: '3.9'
services:
  dockerd:
    image: docker:18.09-dind
    entrypoint: ["dockerd-entrypoint.sh"]
    privileged: true
    expose:
      - 2375/tcp

  docker:
    image: docker:latest
    environment:
      DOCKER_HOST: tcp://dockerd:2375
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
    command:
      ## it's mean run docker info
      - info
    depends_on:
      - dockerd
