version: '3.9'
services:
  postgres:
    image: postgres:12.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=sit_user
      - POSTGRES_DB=sit_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  pg_data: {}
networks:
  backend: {}
