version: '3.8'
services:
  webapp:
    image: nginx:mainline
    ports:
      - "80:80"
  db:
    image: postgres:12.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
