version: '3.9'
services:
  dev-webapp:
    image: nginx:latest
    labels:
      - env=development
    ports:
      - "8081:80"
    volumes:
      - public_html:/usr/share/nginx/html
  stag-webapp:
    image: nginx:mainline
    labels:
      - env=staging
    ports:
      - "80:80"
    volumes:
      - public_html:/usr/share/nginx/html
volumes:
  public_html: {}
