version: '3.9'
services:
  dev-webapp:
    image: nginx:latest
    labels:
      - env=development
    ports:
      - "8082:80"
    volumes:
      - ./html:/usr/share/nginx/html
  stag-webapp:
    image: nginx:mainline
    labels:
      - env=staging
    ports:
      - "81:80"
    volumes:
      - ./html:/usr/share/nginx/html
